apiVersion: v1
kind: Service
metadata:
  name: "svc-{{ include "cache-manager.fullname" . }}"
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app.kubernetes.io/name: {{ include "cache-manager.fullname" . }}
spec:
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ include "cache-manager.fullname" . }}
  type: LoadBalancer