apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cache-manager.fullname" . }}
type: Opaque
stringData:
  appConfigConnectionString: {{ .Values.appConfigConnectionString }}
  redisConnectionString: {{ .Values.redisConnectionString }}