apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bb8-orderstatus-scheduler.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bb8-orderstatus-scheduler.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bb8-orderstatus-scheduler.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bb8-orderstatus-scheduler.fullname" . }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "bb8-orderstatus-scheduler.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        env:
          - name: USE_LOCAL_CONFIG
            value: "false"
          - name: ASPNETCORE_ENVIRONMENT
            value: {{ .Values.environment }}
          - name: FORMER_HOST
            value: {{ .Values.formerHost }}
          - name: ASPNETCORE_URLS
            value: "http://+:80;"
          - name: TZ
            value: America/New_York
          - name: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
            value: "false"
          - name: LC_ALL
            value: en_US.UTF-8
          - name: LANG
            value: en_US.UTF-8
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: http/protobuf
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: {{ .Values.sumoOtelEndpoint }}
          - name: OTEL_SERVICE_NAME
            value: {{ include "bb8-orderstatus-scheduler.fullname" . }}
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "application={{ include "bb8-orderstatus-scheduler.fullname" . }},environment={{ .Values.environment }},deployment.environment={{ .Values.environment }}"
          - name: APP_CONFIG_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: {{ include "bb8-orderstatus-scheduler.fullname" . }}
                key: appConfigConnectionString
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        volumeMounts:
          - name: temp-volume
            mountPath: /temp
          - name: archive-volume
            mountPath: /archive
          - name: archive-ciscosystems-volume
            mountPath: /archive/CiscoSystems
          - name: archive-ingrammicro-volume
            mountPath: /archive/IngramMicro
          - name: archive-techdata-volume
            mountPath: /archive/TechData
        #startupProbe:
        #  httpGet:
        #    path: /health/SP
        #    port: 80
        #  failureThreshold: 25
        #  periodSeconds: 10
        #livenessProbe:
        #  httpGet:
        #    path: /health/LP
        #    port: 80
        #  initialDelaySeconds: 2
        #  periodSeconds: 10
        #  timeoutSeconds: 5
        #  failureThreshold: 10
      volumes:
      - name: temp-volume
        emptyDir:
          medium: Memory
      - name: archive-volume
        emptyDir:
          medium: Memory
      - name: archive-ciscosystems-volume
        emptyDir:
          medium: Memory
      - name: archive-ingrammicro-volume
        emptyDir:
          medium: Memory
      - name: archive-techdata-volume
        emptyDir:
          medium: Memory