apiVersion: v1
kind: Secret
metadata:
  name: "quartz-{{ include "bb8-orderstatus-scheduler.fullname" . }}"
type: Opaque
stringData:
  msSQLSAPassword: {{ .Values.msSQLSAPassword }}
  msSQLQuartzPassword: {{ .Values.msSQLQuartzPassword }}