kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "pvc-quartz-{{ include "bb8-orderstatus-scheduler.fullname" . }}"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed-premium