apiVersion: v1
kind: Service
metadata:
  name: "svc-quartz-{{ include "bb8-orderstatus-scheduler.fullname" . }}"
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
  labels:
    app.kubernetes.io/name: "quartz-{{ include "bb8-orderstatus-scheduler.fullname" . }}"
spec:
  selector:
    app: "quartz-{{ include "bb8-orderstatus-scheduler.fullname" . }}"
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
