apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "windows-agents.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "windows-agents.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "windows-agents.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "windows-agents.fullname" . }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "windows-agents.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        env:
        - name: ADO_ORG_URL
          value: {{ .Values.adoOrgUrl }}
        - name: AGENT_POOL
          value: {{ .Values.agentPool }}
        - name: ADO_PAT
          valueFrom:
            secretKeyRef:
              name: {{ include "windows-agents.fullname" . }}
              key: adopat
        - name: SUMO_LOGIC_INSTALLER_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "windows-agents.fullname" . }}
              key: installtoken
        lifecycle:
          postStart:
            exec:
              command:
              - "powershell.exe"
              - "./poststart.ps1"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}