apiVersion: v1
kind: Secret
metadata:
  name: {{ include "windows-agents.fullname" . }}
type: Opaque
stringData:
  adopat: {{ .Values.adopat }}
  installtoken: {{ .Values.sumologic.installtoken }}