apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qa-user-service.fullname" . }}
type: Opaque
stringData:
  appConfigConnectionString: {{ .Values.appConfigConnectionString }}
  qa2MyOrdersConnectionString: {{ .Values.qa2MyOrdersConnectionString }}
  prodMyOrdersConnectionString: {{ .Values.prodMyOrdersConnectionString }}