apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  presidio.server: |
    presidio.corp:53 {
        errors
        cache 30
        forward presidio.corp. 10.10.10.110 10.27.10.36 168.63.129.16
    }
