resources:
  repositories:
  - repository: QAUserService
    type: git
    name: QAUserService
    trigger:
      branches:
        include:
        - main
  - repository: Pipelines
    type: git
    name: Pipelines
    trigger: none

variables:
- group: ServiceConnections
- group: Snyk
- group: QAUserService
- group: AKSDeployments
- group: Artifacts
- group: Calico
- name: buildNumberPrefix
  value: QA.User.Service
- name: chartPath
  value: 'HelmCharts/QAUserService/Chart'
- name: projectKey
  value: BB8_QAUserService_AYTQIqDwE_xmHebIwIzS
- name: solution
  value: QAUserService.sln
- name: buildConfiguration
  value: Debug
- name: workingDirectory
  value: QAUserService
- name: testDirectory
  value: QAUserService.Tests
- name: testDll
  value: QAUserService.Tests/bin/Debug/net7.0/QAUserService.Tests.dll
- name: sonarQubeConnection
  value: $(ServiceConnections.SonarQubeQAUserService)
- name: breakSonarQubefailure
  value: false
- name: snkyOrganizationId
  value: $(Snyk.OrgIdDevOps)
- name: containerRegistryName
  value: presidiocontainers

parameters:

- name: dockerimagesNetCore
  type: object
  default:

  - repository: qa-user-service
    displayName: QA User Service
    buildContext: 'QAUserService/QAUserService'
    dockerfile: 'Pipelines/HelmCharts/QAUserService/DockerImages/QAUserService/Dockerfile'
    appdll: QAUserService.dll
    failOnIssues: false

- name: environments
  type: object
  default:

  - namespace: qa-agents
    valuesFile: HelmCharts/QAUserService/Chart/values.qa-agents.yaml
    releaseName: qa-user-service
    aksCluster: $(AKSDeployments.BuildAgentsCluster)
    displayName: QA User Service
    continueOnError: false

stages:
- stage: SetBuildNumber
  displayName: Set Build Number
  jobs:
  - job:
    displayName: Set Build Number
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: PowerShell@2
      displayName: Set Build Number
      inputs:
        pwsh: true
        targetType: inline
        script: Write-Host "##vso[build.updatebuildnumber]$(buildNumberPrefix)-$(Build.BuildNumber)"

- stage: RunAutomatedTests
  displayName: Run Automated Tests
  jobs:
  - job:
    displayName: Run Automated Tests
    pool:
      vmImage: windows-latest
    steps:
    - checkout: QAUserService
    - template: HelmCharts\_Templates\applicationTest.yml@Pipelines
      parameters:
        solution: $(solution)
        buildConfiguration: $(buildConfiguration)
        vstsFeed: $(Artifacts.FeedId)
        testDll: $(testDll)

- stage: CodeAnalysis
  displayName: Code Analysis
  jobs:
  - job:
    displayName: Run Snyk Scan
    pool:
      vmImage: windows-latest
    steps:
    - checkout: QAUserService
    - template: SnykScanners/_Templates/snyk.yml@Pipelines
      parameters:
        snykConnection: $(ServiceConnections.SnykAuthentication)
        solution:  ${{ variables.solution }}
        buildConfiguration: ${{ variables.buildConfiguration }}
        vstsFeed: $(Artifacts.FeedId)
        snkyOrganizationId: $(snkyOrganizationId)

  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - job:
      displayName: Run SonarQube Analysis
      pool:
        vmImage: windows-latest
      steps:
      - checkout: QAUserService
      - template: SonarQubeScanners/_Templates/sonarQube.yml@Pipelines
        parameters:
          sonarQubeConnection: $(sonarQubeConnection)
          solution: ${{ variables.solution }}
          buildConfiguration: ${{ variables.buildConfiguration }}
          projectKey: ${{ variables.projectKey }}
          vstsFeed: $(Artifacts.FeedId)
          breakSonarQubefailure: '${{ variables.breakSonarQubefailure }}'
          testDll: ${{ variables.testDll }}
  - ${{ else }}:
    - job:
      displayName: Run SonarQube Analysis
      pool:
        vmImage: windows-latest
      steps:
      - checkout: QAUserService
      - template: SonarQubeScanners/_Templates/sonarQube.yml@Pipelines
        parameters:
          sonarQubeConnection: $(sonarQubeConnection)
          solution: ${{ variables.solution }}
          buildConfiguration: ${{ variables.buildConfiguration }}
          projectKey: ${{ variables.projectKey }}
          vstsFeed: $(Artifacts.FeedId)
          breakSonarQubefailure: '${{ variables.breakSonarQubefailure }}'
          testDll: ${{ variables.testDll }}
          prId: $(System.PullRequest.PullRequestId)
          prSourceBranch: $(System.PullRequest.SourceBranch)
          prTargetBranch: $(System.PullRequest.TargetBranch)

- stage: BuildDockerImages
  displayName: Build Docker Images
  jobs:
  - ${{ each dockerimage in parameters.dockerimagesNetCore }}:
    - job:
      displayName: Build ${{ dockerimage.displayName }} Docker Image
      pool:
        vmImage: ubuntu-latest
      steps:
      - checkout: QAUserService
      - checkout: Pipelines
      - template: HelmCharts/_Templates/dockerApplicationsNetCore.yml@Pipelines
        parameters:
          repository: ${{ dockerimage.repository }}
          buildContext: ${{ dockerimage.buildContext }}
          dockerFile: ${{ dockerimage.dockerFile }}
          failOnIssues: ${{ dockerimage.failOnIssues }}
          appdll: ${{ dockerimage.appDll }}
          containerRegistry: $(ServiceConnections.ContainerRegistry)
          feedUrl: $(Artifacts.FeedUrl)
          accessToken: $(Artifacts.AccessToken)
          feedUser: $(Artifacts.User)
          snykConnection: $(ServiceConnections.SnykAuthentication)
          snkyOrganizationId: $(snkyOrganizationId)
          buildId: $(Build.BuildId)
          registryName: $(Snyk.RegistryName)
          artifactStagingDirectory: $(Build.ArtifactStagingDirectory)
          calicoApi: $(Calico.API)
          calicoToken: $(Calico.Token)
          azureSubscription: $(ServiceConnections.AzureResourceManager)
          containerRegistryName: $(containerRegistryName)

- ${{ each env in parameters.environments }}:
  - stage:
    displayName: Run ${{ env.displayName }} Helm Chart
    jobs:
    - job:
      displayName: Run ${{ env.displayName }} Helm Chart
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: PowerShell@2
          displayName: Replace Tokens for Values YAML
          inputs:
            targetType: inline
            pwsh: true
            script: |
              ((Get-Content -path ${{ env.valuesFile }} -Raw) -replace '~appConfigConnectionString~','$(QAUserService.AppConfigConnectionString)') | Set-Content -Path ${{ env.valuesFile }}
              ((Get-Content -path ${{ env.valuesFile }} -Raw) -replace '~qa2MyOrdersConnectionString~','$(QAUserService.QA2MyOrdersConnectionString)') | Set-Content -Path ${{ env.valuesFile }}
              ((Get-Content -path ${{ env.valuesFile }} -Raw) -replace '~prodMyOrdersConnectionString~','$(QAUserService.ProdMyOrdersConnectionString)') | Set-Content -Path ${{ env.valuesFile }}
              ((Get-Content -path ${{ env.valuesFile }} -Raw) -replace '~buildId~','$(Build.BuildId)') | Set-Content -Path ${{ env.valuesFile }}
              Get-Content -path ${{ env.valuesFile }}

        - task: HelmDeploy@0
          displayName: Run Helm Chart
          continueOnError: ${{ env.continueOnError }}
          inputs:
            connectionType: 'Azure Resource Manager'
            azureSubscriptionEndpoint: $(ServiceConnections.AzureResourceManager)
            azureResourceGroup: $(AKSDeployments.AKSResourceGroup)
            kubernetesCluster: $(AKSDeployments.BuildAgentsCluster)
            azureSubscriptionForACR: $(ServiceConnections.AzureResourceManager)
            azureResourceGroupForACR: $(AKSDeployments.AKSResourceGroup)
            azureContainerRegistry: $(ServiceConnections.ContainerRegistry)
            namespace: ${{ env.namespace }}
            chartPath: $(chartPath)
            valueFile: ${{ env.valuesFile }}
            releaseName: ${{ env.releaseName }}
            command: 'upgrade'
            waitForExecution: true
            chartType: 'FilePath'
            arguments: "--create-namespace --timeout 5m0s"
