apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-crane
subjects:
  - kind: ServiceAccount
    name: default
    namespace: blazemeter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-crane