apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role-crane
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
    apiGroups:
      - ''
    resources:
      - nodes